accounts/urls.py
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

from accounts.views import *

app_name = 'accounts'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path

from blog.feeds import LatestEntriesFeed
from blog.views import *

app_name = "blog"

urlpatterns = [
    path("", blog_view, name="blog_view"),
    path("<int:pid>", blog_single, name="single"),
    path("category/<str:cat_name>", blog_view, name="category"),
    path("tag/<str:tag_name>", blog_view, name="tag"),
    path("author/<str:author_username>", blog_view, name="author"),
    path("search/", blog_search, name="search"),
    path('rss/feed/', LatestEntriesFeed())
]

config/urls.py
import django.contrib.auth.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include, re_path

from blog.sitemaps import BlogSitemap
from main.sitemaps import StaticViewSitemap
from main.views import maintenance_view

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("", include("main.urls")),
    path("blog/", include("blog.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("summernote/", include('django_summernote.urls')),
    path("captcha/", include('captcha.urls')),
    path('', include(django.contrib.auth.urls))
]

if settings.MAINTENANCE_MODE:
    urlpatterns.insert(0, re_path(r'^', maintenance_view, name='maintenance'))

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "main.views.handler404"

main/urls.py
from django.urls import path

from main.views import *

app_name = 'main'

urlpatterns = [
    path("", index_view, name="index_view"),
    path("about/", about_view, name="about"),
    path("contact/", contact_view, name="contact"),
]

templates/base.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html lang="en" itemscope="" itemtype="https://schema.org/None" prefix="og: https://ogp.me/ns#">
<head>
    <meta name="description"
          content="Amirhossein Yazdanpanah Personal Website a Portfolio website with a blog">
    <meta name="keywords"
          content="python, django, 1amiryz1, amirhosseinyazdanpanah, portfolio, personal, blog, 1yzamiryz1,amirhossein, yazdanpanah, software, engineer, backend, developer">
    <meta property="og:title" content="Amirhossein Yazdanpanah Software Engineer | Backend Developer">
    <meta property="og:url" content="https://1amiryz1.ir/">
    <meta property="og:description"
          content="Amirhossein Yazdanpanah Personal Website a Portfolio website with a blog">
    <meta property="og:image" content="https://1amiryz1.ir/static/img/profile.jpg">
    <meta property="og:image:secure_url" content="https://1amiryz1.ir/static/img/profile.jpg">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="1amiryz1">
    <meta property="og:locale" content="fa_IR">
    <meta name="twitter:card" content="https://1amiryz1.ir/static/img/profile.jpg">
    <meta name="twitter:domain" content="1amiryz1.ir">
    <meta name="twitter:title" content="Amirhossein Yazdanpanah Software Engineer | Backend Developer">
    <meta name="twitter:url" content="https://1amiryz1.ir/">
    <meta name="twitter:description"
          content="Amirhossein Yazdanpanah Personal Website a Portfolio website with a blog">
    <meta name="twitter:image" content="https://1amiryz1.ir/static/img/profile.jpg">
    <meta itemprop="name" content="Amirhossein Yazdanpanah Software Engineer | Backend Developer">
    <meta itemprop="url" content="https://1amiryz1.ir/">
    <meta itemprop="description"
          content="Amirhossein Yazdanpanah Personal Website a Portfolio website with a blog">
    <meta itemprop="image" content="https://1amiryz1.ir/static/img/profile.jpg">


    <title>{% block title %} {% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <!-- Google Web Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/android-chrome-512x512' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/android-chrome-192x192' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/site.webmanifest' %}">
    {% compress css %}

        <link rel="stylesheet" href="{% static 'css/search.css' %}">
        <link rel="stylesheet" href="{% static 'css/comments.css' %}">


        <!-- Libraries Stylesheet -->
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% endcompress %}
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="51">
<!-- Navbar Start -->
<nav class="navbar fixed-top shadow-sm navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-lg-5">
    <a title="main" href="{% url 'main:index_view' %}" class="navbar-brand ml-lg-3">
        <h1 class="m-0 display-5"><span class="text-primary">Am</span>ir</h1>
    </a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse px-lg-3" id="navbarCollapse">
        <div class="navbar-nav m-auto py-0">
            {% if request.get_full_path == '/' %}
                <a title='main' href="{% url 'main:index_view' %}" class="nav-item nav-link active">Home</a>
                <a title="about" href="{% url 'main:about' %}" class="nav-item nav-link">About</a>
                <a title="quality" href="#qualification" class="nav-item nav-link">Quality</a>
                <a title="skill" href="#skill" class="nav-item nav-link">Skill</a>
                <a title="service" href="#service" class="nav-item nav-link">Service</a>
                <a title="portfolio" href="#portfolio" class="nav-item nav-link">Portfolio</a>
                <a title="blog" href="{% url 'blog:blog_view' %}" class="nav-item nav-link">Blog</a>
                <a title="contact" href="{% url 'main:contact' %}" class="nav-item nav-link">Contact</a>
            {% else %}
                <a title="main" href="{% url 'main:index_view' %}" class="nav-item nav-link active">Home</a>
                <a title="about" href="{% url 'main:about' %}" class="nav-item nav-link">About</a>
                <a title="blog" href="{% url 'blog:blog_view' %}" class="nav-item nav-link">Blog</a>
                <a title="contact" href="{% url 'main:contact' %}" class="nav-item nav-link">Contact</a>
            {% endif %}
            {% if request.user.is_authenticated %}

                <a title="user" href="#" class="nav-item nav-link">Logged in as {{ request.user.username }}</a>


                <a title="logout" href="{% url 'accounts:logout' %}" class="nav-item nav-link">Logout</a>

            {% else %}

                <a title="login" href="{% url 'accounts:login' %}" class="nav-item nav-link">Login</a>


                <a title="signup" href="{% url 'accounts:signup' %}" class="nav-item nav-link">SignUp</a>

            {% endif %}
        </div>
    </div>
</nav>
<!-- Navbar End -->
{% include 'pop-up.html' %}
<!-- Header Start -->
<div class="container-fluid bg-primary d-flex align-items-center mb-5 py-5" id="home" style="min-height: 100vh;">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 px-5 pl-lg-0 pb-5 pb-lg-0">
                <img class="img-fluid w-100 rounded-circle shadow-sm" src="{% static 'img/profile.jpg' %}" alt="Me">
            </div>
            <div class="col-lg-7 text-center text-lg-left">
                <h3 class="text-white font-weight-normal mb-3">I'm</h3>
                <h1 class="display-3 text-uppercase text-primary mb-2" style="-webkit-text-stroke: 2px #ffffff;">
                    AmirHossein<br>YazdanPanah</h1>
                <h1 class="typed-text-output d-inline font-weight-lighter text-white"></h1>
                <div class="typed-text d-none">Web Designer, Web Developer, Back End Developer, Apps Designer, Apps
                    Developer
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Header End -->
{% block content %}

{% endblock %}
<!-- Footer Start -->
<div class="container-fluid bg-primary text-white mt-5 py-5 px-sm-3 px-md-5">
    <div class="container text-center py-5">
        <div class="d-flex justify-content-center mb-4">
            <a title="github" class="btn btn-light btn-social mr-2" href="https://github.com/1yzamiryz1"><i
                    class="fab fa-github"></i></a>
            <a title="telegram" class="btn btn-light btn-social mr-2" href="https://www.t.me/Amirhosseinyz1"><i
                    class="fab fa-telegram"></i></a>
            <a title="linkedin" class="btn btn-light btn-social mr-2" href="https://www.linkedin.com/in/1amiryz1"><i
                    class="fab fa-linkedin-in"></i></a>
            <a title="instagram" class="btn btn-light btn-social" href="https://www.instagram.com/1amiryz1"><i
                    class="fab fa-instagram"></i></a>
        </div>
        <p style="display: none;" class="m-0">&copy; <a title="domain" class="text-white font-weight-bold" href="#">Domain
            Name</a>.
            All Rights Reserved.
            Designed by <a title="html" class="text-white font-weight-bold" href="https://htmlcodex.com">HTML Codex</a>
        </p>
        <p class="m-0"><a title="1amiryz1.ir" class="text-white font-weight-bold" href="#">1amiryz1.ir</a>. All Rights
            Reserved.
            Designed by <a title="1amiryz1" class="text-white font-weight-bold" href="#">1amiryz1</a></p>
    </div>
</div>
<!-- Footer End -->

<!-- Scroll to Bottom -->
<i class="fa fa-2x fa-angle-down text-white scroll-to-bottom"></i>

<!-- Back to Top -->
<a title="top" href="#" class="btn btn-outline-dark px-0 back-to-top"><i class="fa fa-angle-double-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js">
</script>
{% compress js %}
    <script src="{% static 'lib/typed/typed.min.js' %}"></script>

    <script src="{% static 'lib/easing/easing.min.js' %}"></script>

    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>

    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>

    <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
{% endcompress %}
</body>

</html>

templates/maintenance.html
<!doctype html>
<title>Site Maintenance</title>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
<style>
    html, body {
        padding: 0;
        margin: 0;
        width: 100%;
        height: 100%;
    }

    * {
        box-sizing: border-box;
    }

    body {
        text-align: center;
        padding: 0;
        background: #d6433b;
        color: #fff;
        font-family: Open Sans;
    }

    h1 {
        font-size: 50px;
        font-weight: 100;
        text-align: center;
    }

    body {
        font-family: Open Sans;
        font-weight: 100;
        font-size: 20px;
        color: #fff;
        text-align: center;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
    }

    article {
        display: block;
        width: 700px;
        padding: 50px;
        margin: 0 auto;
    }

    a {
        color: #fff;
        font-weight: bold;
    }

    a:hover {
        text-decoration: none;
    }

    svg {
        width: 75px;
        margin-top: 1em;
    }
</style>

<article>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 202.24 202.24">
        <defs>
            <style>.cls-1 {
                fill: #fff;
            }</style>
        </defs>
        <title>Asset 3</title>
        <g id="Layer_2" data-name="Layer 2">
            <g id="Capa_1" data-name="Capa 1">
                <path class="cls-1"
                      d="M101.12,0A101.12,101.12,0,1,0,202.24,101.12,101.12,101.12,0,0,0,101.12,0ZM159,148.76H43.28a11.57,11.57,0,0,1-10-17.34L91.09,31.16a11.57,11.57,0,0,1,20.06,0L169,131.43a11.57,11.57,0,0,1-10,17.34Z"/>
                <path class="cls-1"
                      d="M101.12,36.93h0L43.27,137.21H159L101.13,36.94Zm0,88.7a7.71,7.71,0,1,1,7.71-7.71A7.71,7.71,0,0,1,101.12,125.63Zm7.71-50.13a7.56,7.56,0,0,1-.11,1.3l-3.8,22.49a3.86,3.86,0,0,1-7.61,0l-3.8-22.49a8,8,0,0,1-.11-1.3,7.71,7.71,0,1,1,15.43,0Z"/>
            </g>
        </g>
    </svg>
    <h1>We&rsquo;ll be back soon!</h1>
    <div>
        <p>Sorry for the inconvenience. We&rsquo;re performing some maintenance at the moment. we&rsquo;ll be back up
            shortly!</p>
        <p>&mdash; The [1amiryz1] Team</p>
    </div>
</article>

templates/pop-up.html
{% load static %}

{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %} alert-{{ message.tags }} alert-dismissible fade show{% endif %}">{{ message|safe }}</div>
    {% endfor %}
{% endif %}

{% if form.errors %}
    <div class="alert alert-error">
        <h4>Please fix the following errors</h4>
        <ul>
            {% for field in form %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </ul>
        {% if form.non_field_errors %}
            {{ form.non_field_errors }}
        {% endif %}
    </div>
{% endif %}